### ISSUE TITLE
Recurring payments

### ISSUE THREAD

**Issue by anesuc** [adyen-examples/adyen-node-online-payments#42]
Hi,

I have been having difficulty trying to figure out how to setup recurring payments with this. The documentation on this (recurring payments) isn't as clear as I would like (for me anyway). Any samples or direction on how I would adjust something like this to have recurring payments?

Thanks

**Comment by jlengrand** [comment]
Hey @anesuc ,

you are correct, that sample does not support take recurring payments. I'll add this to our list of samples in the future 😊.

In the meantime, I created a [merge request](https://github.com/adyen-examples/adyen-node-online-payments/pull/43/files) with the changes you should make to the sample for it to accept recurring payments. 
I took the example of subscriptions but you should be able to implement any of the scenarios mentioned [here](https://docs.adyen.com/online-payments/tokenization/create-and-use-tokens) with minor changes. 

In short, we need to start tokenizing the payment information received, so they can be reused in the future. We do this by adding extra information in our `/sessions` or `/ payments` call 

```
      shopperInteraction : "Ecommerce",
      recurringProcessingModel: "Subscription",
      storePaymentMethod: true,
```

(Note that you can also enable tokenisation for other things than recurring payments, for example to avoid your customers having to insert their card information again in future visits). See [here](https://docs.adyen.com/payment-methods/cards/web-drop-in#stored-card-payments) for more information.

Then, you need to be ready to receive the `shopperReference` and `recurringDetailReference` information that will be returned in the notifications once the payments has been validated.

You can do this in two ways : 

* By enabling `recurring details` in your customer area Developers -> Additional data. In this case, you will receive the information in the additional data block of the AUTHORIZATION webhook notification

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/921666/171603868-3b18293b-9523-4abe-bd0f-e2bbbe9fc38a.png">

* By enabling the specific `RECURRING_CONTRACT` event code webhook by going to Developers -> Webhooks and then clicking on the settings button

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/921666/171604324-b00db37a-bde7-4bcb-88f5-d03cefae291c.png">

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/921666/171604262-48414c84-7bf2-4990-8028-dfdcf6d58d0b.png">

You will then start receiving additional notifications. This is the choice I have made in the merge request. 

In both cases, you should start capturing that information on your end, and coupling it with your unique customer ID and probably the date of recurring payment. 

At that point, you can use that information to initiate future payments yourself from the server side, for example by daily batches. I added an example of such a call in the merge request, though note that in my case it is not connected to anything because the sample is not made for it.

Hope that helps! Let me know if you have any additional question!

**Comment by anesuc** [comment]
Fantastic! Let me try this

**Comment by anesuc** [comment]
Hi @jlengrand 

Thanks for the well documented response! I have been getting the error `Erro validating HMAC Signature recurring is not defined`.
Any suggestions as to why this might be? I have re-gnerrated the HMAC Key just incase to no avail.

Thanks

**Comment by anesuc** [comment]
Hi again,

Sorry, my bad, I figured it out. Just needed quotes around 'recurring.shopperReference' and 'recurring.recurringDetailReference'.

i.e

```
console.log('shopperReference:' + notification.additionalData['recurring.shopperReference']);
console.log('recurring.recurringDetailReference:' + notification.additionalData['recurring.recurringDetailReference']);
```

**Comment by jlengrand** [comment]
Great to hear. Did you manage to get it all working?

**Comment by anesuc** [comment]
Hi @jlengrand ,

Sorry ended up being pretty busy in the last couple of days. It works! However, when I make a payment using the stored details on renewal, I have no idea who it belongs to as I don't get shopperReference back from the AUTHORISATION event on the webhook(which is the only event I receive at this point. Note this is not during the initial payment but further payments).

The second one related to this, the user has to click "save for my next payment" which for my use-case has to be by default as this is for a subscription account. If they don't I also don't get the recurring details (for obvious reasons) alongside the shopperReference and therefore don't know who it belongs to. Maybe if there is a way to check before processing to let the user know they need to enable it when paying for a subscription then that would be great. This is because there is other payment options not subscription related. But for subscriptions I want to be sure I can process it at the end of the month (well as long as the card is active etc).

Thanks again!

**Comment by anesuc** [comment]
@jlengrand Sorry for the late reply, was away for a bit. Started working on this but hadn't finished testing things related to this so waited to reply. I'll update this later today!

**Comment by anesuc** [comment]
Hi @jlengrand ,

I finally managed to have time today to work on this! Ok, so I now get the info on authorisation BUT when I go to renew/get another payment I don't get back the shopper reference but I did notice I get the recurring reference so I just adjusted things to use that to find the username on the backend.

Thanks for the help really appreciate it!

**Comment by anesuc** [comment]
I have updated the comment above, this was an issue on my end. I just realised the email notifications on this won't show the edits s I thought I would make a new one clarifying.

**Comment by jlengrand** [comment]
Alright, that's great to hear 😊.

Can I close the issue?

**Comment by anesuc** [comment]
Yep thanks! I'll do it now actually!
